name: CI/CD Pipeline for Spring Boot to Azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test with Gradle
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. JDK 설정
      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      # 3. Gradle 빌드 및 테스트
      - name: Build and Test with Gradle
        run: |
          ./gradlew clean build

      # 4. 빌드 아티팩트 저장
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-app
          path: build/libs/*.jar

  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: build  # 빌드 및 테스트 이후 실행

    steps:
      # 1. 빌드 결과 다운로드
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: spring-boot-app
          path: build/libs/

      # 2. Azure 로그인
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3. Azure Web App 배포
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: build/libs/*.jar